### SRC SHOP HACK TOOL ###
### BETA VERSION 3.0 ###
### System > Python Value ###
### AUTHOR XOIX19 ###
### github.com/xoix19 ###

import os
import sys
import time
import socket
import random

def logo():
print ("──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────")
print ("─██████████████─██████──██████─██████████████─██████████████────██████──██████─██████████████─██████████████─██████──████████─")
print ("─██░░░░░░░░░░██─██░░██──██░░██─██░░░░░░░░░░██─██░░░░░░░░░░██────██░░██──██░░██─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░██──██░░░░██─")
print ("─██░░██████████─██░░██──██░░██─██░░██████░░██─██░░██████░░██────██░░██──██░░██─██░░██████░░██─██░░██████████─██░░██──██░░████─")
print ("─██░░██─────────██░░██──██░░██─██░░██──██░░██─██░░██──██░░██────██░░██──██░░██─██░░██──██░░██─██░░██─────────██░░██──██░░██───")
print ("─██░░██████████─██░░██████░░██─██░░██──██░░██─██░░██████░░██────██░░██████░░██─██░░██████░░██─██░░██─────────██░░██████░░██───")
print ("─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░██──██░░██─██░░░░░░░░░░██────██░░░░░░░░░░██─██░░░░░░░░░░██─██░░██─────────██░░░░░░░░░░██───")
print ("─██████████░░██─██░░██████░░██─██░░██──██░░██─██░░██████████────██░░██████░░██─██░░██████░░██─██░░██─────────██░░██████░░██───")
print ("─────────██░░██─██░░██──██░░██─██░░██──██░░██─██░░██────────────██░░██──██░░██─██░░██──██░░██─██░░██─────────██░░██──██░░██───")
print ("─██████████░░██─██░░██──██░░██─██░░██████░░██─██░░██────────────██░░██──██░░██─██░░██──██░░██─██░░██████████─██░░██──██░░████─")
print ("─██░░░░░░░░░░██─██░░██──██░░██─██░░░░░░░░░░██─██░░██────────────██░░██──██░░██─██░░██──██░░██─██░░░░░░░░░░██─██░░██──██░░░░██─")
print ("─██████████████─██████──██████─██████████████─██████────────────██████──██████─██████──██████─██████████████─██████──████████─")
print ("──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────")

def createaccount():
    name = raw_input("Your Name:")
    phone = raw_input("Your Phone:")
    passwords = raw_input("Input Your Pass:")
    address = raw_inpur("Input Your Addres:")
    time.sleep(2.0)
    print ("")
    print ("Message > Create Account Please Wait..")
    time.sleep(9.0)
    os.system("Message > Succes Create Account..")
    time.sleep(1.0)
    
def login():
    srh = raw_input("Y/n:")
    if srh =='Y':
        os.system("account.py")
    elif srh =='n':
        os.system("exit")
    
def options():
    print ("Options:")
    print ("[1] Create Account SHOPHACK")
    print ("[2] Login Account SHOPHACK")
    print ("[0] Exit?")
    pil = raw_input("Select>:")
    if pil =='1':
        createaccount()
    elif pil =='2':
        login()
    else:
        print ("Opps { : }")
        
print ("### README ###")
print ("Please don't use this tool repeatedly, if you use it repeatedly, the tool won't work.")
print ("Please use the same network when logging in or creating an account, so that there is no error sending data to the server and so that the tool is not damaged.")
print ("this tool is very sensitive sorry :)")
print ("")
print ("### AUTHOR PROFILE ###")
print ("github.com/xoix19")
print ("Author : XOIX19")
print ("MAIL   : wearexoix19@secmail.pro")
print ("Happy Use :)")
time.sleep(9.0)
os.system("clear")

print ("Message > Adding source code")
time.sleep(3.0)
print ("")
print ("Succes Added :)")
time.sleep(4.0)
os.system("clear")
print ("Message > Added Logo..")
time.sleep(5.0)
print ("Message > Succes Added.. [Load Logo]")
time.sleep(2.0)
os.system("clear")

logo()
options()
time.sleep(3.0)
os.system("clear")
print ("[ Congratulations you have entered this area ]")
print ("")
print (" [ Enter the URL of the item to be purchased ]")
url = raw_input("[?]Url:")
time.sleep(4.0)
print ("Message > Checking the Url ..")
time.sleep(5.0)
print ("")
print ("Message > Retrieving data, to be manipulated..")
time.sleep(9.0)
print ("Message > Successfully Retrieving Data ... Please Wait While Manipulating Server ...")
time.sleep(9.0)
print ("")
print ("Message > Succes Manipulated.. Please Wait..")
print ("Message > Load Addres..")
time.sleep(1.0)
print ("Message > Load Name..")
time.sleep(1.0)
print ("Message > Load Phone Number..")
time.sleep(1.0)
print ("Message > telnet Url..")
time.sleep(5.0)
print ("Message > Telnet Failed :(")
time.sleep(4.0)
print ("Message > Retrying Telnet This Url ..")
time.sleep(7.0)
print ("Message > Succes Telnet This Url ..")
time.sleep(1.0)
print ("Check Module Source Code..")
time.sleep(1.0)
print ("Succes Check Module")
time.sleep(1.0)
print ("Delete Log Source Code...")
time.sleep(3.0)
print ("Succes Delete Log")
time.sleep(4.0)
print ("Terminal } System End ")
time.sleep(4.0)
os.system("clear")
name = raw_input("Your Name:")
time.sleep(4.0)
phone = raw_input("Your Phone:")
time.sleep(3.0)
print ("")
print ("Inggris:")
print ("Currently Shopping :)")
print ("Please be patient. Please wait 3-6 days for the goods to arrive ... Make sure the address is correct")
time.sleep(4.0)
print ("Indonesian:")
print ("Saat ini Berbelanja :)")
print ("Harap bersabar. Mohon tunggu 3-6 hari sampai barang tiba ... Pastikan alamat sudah benar")
time.sleep(5.0)
print ("")
print ("### GOOD BYE ###")
print ("Jika Barang Tidak Kunjung Datang Silahkan Contack Saya:")
print ("wearexoix19@secmail.pro")
print ("")
print ("### SYSTEM } SHUTDOWN")
